### ISSUE TITLE
Not working for new android devices

### ISSUE THREAD

**Issue by derekhe** [Vidarls/legoremote#1]
This demo app can't run for modern android devices (6 and 7 or above), I just use the LegoRCProtocol and combine with another ir lib to make it work, see here:
https://github.com/derekhe/lego-ir-remote

**Comment by Vidarls** [comment]
Well hello there.

I had almost completely forgotten about this project, (as I had a phone without IR blaster for a while).

Happy that you were able to use parts of it :)

-Vidar

(Closing the issue, as I have no intention of actually fixing the problem.)
